markdown: kramdown
theme: jekyll-theme-minimal
title: SouthCentralCommunity.com
description: Information about the technology related groups and events in the TOLA Region (Texas, Oklahoma, Louisiana & Arkansas)
google_analytics: UA-128027829-1

collections:
  events:
    output: true
    hide: false
  groups:
    output: true
    hide: false
  states:
    output: true
    permalink: /states/:path/
  regions:
    output: true
    permalink: /regions/:path/
  topics:
    output: true
    permalink: /topics/:path/
    
defaults:
  -
    scope:
      path: "" 
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: "" 
      type: "regions"
    values:
      layout: "region"
  -
    scope:
      path: "" 
      type: "states"
    values:
      layout: "state"
