markdown: kramdown
theme: jekyll-theme-minimal
title: SouthCentralCommunity.com
description: Information about the groups and events in the TOLA Region (Texas, Oklahoma, Louisiana & Arkansas)

collections:
  - events
  - groups