markdown: kramdown
theme: jekyll-theme-minimal
title: SouthCentralCommunity.com
description: Information about the technology related groups and events in the TOLA Region (Texas, Oklahoma, Louisiana & Arkansas)

collections:
  events:
    output: true
  groups:
    output: true
  states:
    output: true
    permalink: /states/:path/
  regions:
    output: true
    permalink: /regions/:path/
  topics:
    output: true
    permalink: /topics/:path/
    
defaults:
  -
    scope:
      path: "" 
      type: "topics"
    values:
      layout: "topic"
